# """
# Django settings for core project.

# Generated by 'django-admin startproject' using Django 5.2.1.
# """

# from datetime import timedelta
# from pathlib import Path

# from decouple import config

# BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET_KEY = config("DJANGO_SECRET_KEY", default="change-me")

# DEBUG = config("DJANGO_DEBUG", default="False") in ["True", "true", "1", "yes", "YES"]

# ALLOWED_HOSTS = config(
#     "DJANGO_ALLOWED_HOSTS", default="127.0.0.1,localhost,backend,api,0.0.0.0"
# ).split(",")

# APPEND_SLASH = False

# CSRF_TRUSTED_ORIGINS = config(
#     "DJANGO_CSRF_TRUSTED_ORIGINS",
#     default="http://127.0.0.1:3000,http://localhost:3000",
# ).split(",")

# BASE_URL = config("BASE_URL", default="http://127.0.0.1:8000")
# FRONTEND_BASE_URL = config("FRONTEND_URL", default="http://127.0.0.1:3000")

# CORS_ALLOWED_ORIGINS = config(
#     "CORS_ALLOWED_ORIGINS", default="http://localhost:3000,http://127.0.0.1:3000"
# ).split(",")

# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "django_filters",
#     "corsheaders",
#     "accounts",
#     "courses.apps.CoursesConfig",
#     "dashboard",
#     "rest_framework",
#     "rest_framework_simplejwt",
# ]

# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# # ✅ Projeto correto é "core" (não "eduplatform")
# ROOT_URLCONF = "core.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# # ✅ Projeto correto é "core" (não "eduplatform")
# WSGI_APPLICATION = "core.wsgi.application"

# # ✅ DB_HOST default "db" para Docker (evita socket /run/mysqld/mysqld.sock)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "HOST": config("DB_HOST", default="db"),
#         "NAME": config("DB_NAME", default="grfcourses"),
#         "USER": config("DB_USER", default="grfcourses"),
#         "PASSWORD": config("DB_PASSWORD", default="grfcourses"),
#         "PORT": config("DB_PORT_INTERNAL", default="3306", cast=int),
#         "OPTIONS": {
#             "charset": "utf8mb4",
#         },
#     }
# }

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
#     },
#     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
#     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
#     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
# ]

# AUTH_USER_MODEL = "accounts.User"

# LANGUAGE_CODE = "pt-br"
# TIME_ZONE = "America/Sao_Paulo"
# USE_I18N = True
# USE_TZ = True

# STATIC_URL = "static/"
# STATIC_ROOT = BASE_DIR / "staticfiles"

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST_FRAMEWORK = {
#     "EXCEPTION_HANDLER": "core.utils.custom_exception.custom_exception_handler",
#     "DEFAULT_RENDERER_CLASSES": ["core.utils.renderers.CustomJSONRenderer"],
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ),
#     "DEFAULT_PERMISSION_CLASSES": [
#         "rest_framework.permissions.IsAuthenticated",
#     ],
#     "DEFAULT_FILTER_BACKENDS": [
#         "django_filters.rest_framework.DjangoFilterBackend",
#         "rest_framework.filters.OrderingFilter",
#     ],
#     "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
#     "PAGE_SIZE": 12,
# }

# SIMPLE_JWT = {"ACCESS_TOKEN_LIFETIME": timedelta(days=7)}

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""

from datetime import timedelta
from pathlib import Path

from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config("DJANGO_SECRET_KEY", default="change-me")

DEBUG = config("DJANGO_DEBUG", default="False") in ["True", "true", "1", "yes", "YES"]

ALLOWED_HOSTS = config(
    "DJANGO_ALLOWED_HOSTS", default="127.0.0.1,localhost,backend,api,0.0.0.0"
).split(",")

APPEND_SLASH = False

CSRF_TRUSTED_ORIGINS = config(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default="http://127.0.0.1:3000,http://localhost:3000",
).split(",")

BASE_URL = config("BASE_URL", default="http://127.0.0.1:8000")
FRONTEND_BASE_URL = config("FRONTEND_URL", default="http://127.0.0.1:3000")

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS", default="http://localhost:3000,http://127.0.0.1:3000"
).split(",")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "corsheaders",
    "accounts",
    "courses.apps.CoursesConfig",
    "dashboard",
    "rest_framework",
    "rest_framework_simplejwt",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ✅ Projeto correto é "core" (não "eduplatform")
ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ✅ Projeto correto é "core" (não "eduplatform")
WSGI_APPLICATION = "core.wsgi.application"

# ✅ DB_HOST default "db" para Docker (evita socket /run/mysqld/mysqld.sock)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": config("DB_HOST", default="db"),
        "NAME": config("DB_NAME", default="grfcourses"),
        "USER": config("DB_USER", default="grfcourses"),
        "PASSWORD": config("DB_PASSWORD", default="grfcourses"),
        "PORT": config("DB_PORT_INTERNAL", default="3306", cast=int),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

AUTH_USER_MODEL = "accounts.User"

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "core.utils.custom_exception.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": ["core.utils.renderers.CustomJSONRenderer"],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
}

SIMPLE_JWT = {"ACCESS_TOKEN_LIFETIME": timedelta(days=7)}
